version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/apps/mcp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib/core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/lib/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/modules/typescript-ivm"
    schedule:
      interval: "weekly"
